ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_gender INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_height DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_weight DOUBLE PRECISION;
